### PR TITLE
Add SIGTRAP to LoggerCrash to enable null dereferences capture on iOS…

### PR DESCRIPTION
**Pull request by DanielAsher**
… devices.

This is a fairly straight-forward addition of SIGTRAP to enable fuller crash reporting on iOS devices.

### CODE REVIEW

**Comment by remirobert** [comment]
awesome contribution thanks

**Comment by DanielAsher** [comment]
I would suggest that this needs more thorough testing - I've not yet pushed it out to TestFlight where the release build, App Store, bitcode etc. may render it non-functional. I don't believe there should be any negative consequences though. I'll report back when I get some data on this...

**Comment by remirobert** [comment]
Yes no negative consequences. The crash reporter is a good feature, but currently the implementation in Dotzu is quite basic. Thanks anyway to contributing in the project.

**Comment by CocoaDebug** [comment]
Hi, I released [DebugMan](https://github.com/liman123/DebugMan), it is forked from [Dotzu](https://github.com/remirobert/Dotzu).
Welcome to use! 😃 thanks!
@DanielAsher

**Pull request merged**
