### PR TITLE
Added CocoaPods installation

### PR DESCRIPTION
**Pull request by lfarah**

### CODE REVIEW

**Comment by remirobert** [comment]
Thank you so much for your contribution. It's pretty clean.
But I prefer don't add the cocoapods documentation on the README for now. I have a issue with the statics resources (Xibs, Storyboards, and Images).

All the resources of available on the Pods folder, but I can't instantiate them on the code.
If you have a clue 😜

**Comment by lfarah** [comment]
@hyperoslo can you guys give it a ✋?

**Comment by lfarah** [comment]
Ohhhh, resources are a huuuuuuuuuuuge pain for CocoaPods!

**Comment by remirobert** [comment]
I didn't know that before.... 😢

**Comment by CocoaDebug** [comment]
Hi, I released [DebugMan](https://github.com/liman123/DebugMan), it is forked from [Dotzu](https://github.com/remirobert/Dotzu).
Welcome to use! 😃 thanks!
@lfarah

**Pull request merged**
